runtime: go
api_version: go1

includes: 
- skiplist.yaml

handlers:
- url: /siegfried/identify
  script: _go_app
  secure: always

- url: /siegfried/sets
  script: _go_app
  secure: always

- url: /siegfried/update
  script: _go_app
  secure: always

- url: /siegfried/results/.*
  script: _go_app
  secure: always

- url: /siegfried/latest
  static_files: public/latest/default.sig
  upload: public/latest/default.sig
  secure: always

- url: /(.*\..*)
  static_files: public/\1
  upload: public/(.*\..*)
  secure: always

- url: /(.+)/
  static_files: public/\1/index.html
  upload: public/(.+)/index.html
  secure: always

- url: /(.+)
  static_files: public/\1/index.html
  upload: public/(.+)/index.html
  secure: always

- url: /
  static_files: public/index.html
  upload: public/index.html
  secure: always








