runtime: go
api_version: go1

includes: 
- skiplist.yaml

handlers:
- url: /siegfried/(identify|results|sets|update|share|redact).*
  script: _go_app
  secure: always

- url: /siegfried/latest
  static_files: public/latest/default.sig
  upload: public/latest/default.sig
  secure: always
  application_readable: true

- url: /siegfried/latest/(loc|tika|freedesktop|pronom-tika-loc|deluxe)$
  static_files: public/latest/\1.sig
  upload: public/latest/(loc|tika|freedesktop|pronom-tika-loc|deluxe).sig$
  secure: always
  application_readable: true

- url: /(.*\.(html|xml|png|jpg|gif|css|js))$
  static_files: public/\1
  upload: public/.*\.(html|xml|png|jpg|gif|css|js)$
  secure: always

- url: /((about|siegfried|post|categories|tags).*)/$
  static_files: public/\1/index.html
  upload: public/(about|siegfried|post|categories|tags).*/index.html$
  secure: always

- url: /((about|siegfried|post|categories|tags).*)
  static_files: public/\1/index.html
  upload: public/(about|siegfried|post|categories|tags).*/index.html$
  secure: always

- url: /$
  static_files: public/index.html
  upload: public/index.html
  secure: always

- url: /.*
  script: _go_app
  secure: always