application: itforarchivists
version: 1
runtime: go
api_version: go1

handlers:
- url: /blog/css
  static_dir: public/blog/css
  expiration: "30d"

- url: /blog/img
  static_dir: public/blog/img
  expiration: "30d"

- url: /blog/(.+)/
  static_files: public/blog/\1/index.html
  upload: public/blog/(.+)/index.html

- url: /blog/(.+)
  static_files: public/blog/\1/index.html
  upload: public/blog/(.+)/index.html

- url: /blog/
  static_files: public/blog/index.html
  upload: public/blog/index.html

- url: /blog
  static_files: public/blog/index.html
  upload: public/blog/index.html

- url: /js
  static_dir: public/js
  expiration: "30d"

- url: /css
  static_dir: public/css
  expiration: "30d"

- url: /img
  static_dir: public/img
  expiration: "30d"

- url: /.*
  script: _go_app