runtime: go116

includes: 
- env.yaml

handlers:
- url: /dists
  static_dir: public/repositories/dists

- url: /pool
  static_dir: public/repositories/pool

- url: /siegfried/sets/(.*\.json)$
  static_files: public/sets/\1
  upload: public/sets/(.*\.json)$
  secure: always

- url: /siegfried/(identify|results|sets|update|share|redact|jobs|logs|benchmarks|develop).*
  script: auto
  secure: always

- url: /siegfried/latest
  static_files: public/latest/default.sig
  upload: public/latest/default.sig
  secure: always

- url: /siegfried/latest/(loc|tika|freedesktop|pronom-tika-loc|deluxe|wikidata)$
  static_files: public/latest/\1.sig
  upload: public/latest/(loc|tika|freedesktop|pronom-tika-loc|deluxe|wikidata).sig$
  secure: always

- url: /(.*\.(html|xml|png|jpg|gif|css|js))$
  static_files: public/\1
  upload: public/.*\.(html|xml|png|jpg|gif|css|js)$
  secure: always

- url: /((about|siegfried|post|categories|tags).*)/$
  static_files: public/\1/index.html
  upload: public/(about|siegfried|post|categories|tags).*/index.html$
  secure: always

- url: /((about|siegfried|post|categories|tags).*)
  static_files: public/\1/index.html
  upload: public/(about|siegfried|post|categories|tags).*/index.html$
  secure: always

- url: /$
  static_files: public/index.html
  upload: public/index.html
  secure: always

- url: /.*
  script: auto
  secure: always