application: itforarchivists
version: 1
runtime: go
api_version: go1

handlers:
- url: /js
  static_dir: public/js
  expiration: "30d"

- url: /css
  static_dir: public/css
  expiration: "30d"

- url: /img
  static_dir: public/img
  expiration: "30d"

- url: /.*
  script: _go_app