runtime: go120

app_engine_apis: true

includes: 
- env.yaml

handlers:
- url: /robots.txt$
  static_files: public/robots.txt
  upload: public/robots.txt$

- url: /sitemap.xml$
  static_files: public/sitemap.xml
  upload: public/sitemap.xml$

- url: /dists
  static_dir: public/repositories/dists

- url: /pool
  static_dir: public/repositories/pool

- url: /siegfried/sets/(.*\.json)$
  static_files: public/sets/\1
  upload: public/sets/(.*\.json)$
  secure: always

- url: /siegfried/(identify|results|sets|share|redact|jobs|logs|benchmarks|develop).*
  script: auto
  secure: always

- url: /siegfried/update$
  http_headers: 
    Content-Type: "application/json; charset=utf-8"
    Access-Control-Allow-Origin: '*'
  static_files: public/update/update.json
  upload: public/update/update.json$
  secure: always

- url: /siegfried/update/(loc|tika|freedesktop|deluxe|wikidata|archivematica)$
  http_headers:
    Content-Type: "application/json; charset=utf-8" 
    Access-Control-Allow-Origin: '*'
  static_files: public/update/\1.json
  upload: public/update/(loc|tika|freedesktop|deluxe|wikidata|archivematica).json$
  secure: always

- url: /siegfried/update/v2$
  http_headers: 
    Content-Type: "application/json; charset=utf-8"
    Access-Control-Allow-Origin: '*'
  static_files: public/update/v2/update.json
  upload: public/update/v2/update.json$
  secure: always

- url: /siegfried/update/v2/(loc|tika|freedesktop|deluxe|wikidata|archivematica)$
  http_headers: 
    Content-Type: "application/json; charset=utf-8"
    Access-Control-Allow-Origin: '*'
  static_files: public/update/v2/\1.json
  upload: public/update/v2/(loc|tika|freedesktop|deluxe|wikidata|archivematica).json$
  secure: always

- url: /siegfried/latest/(1_10|1_11)/(default|loc|tika|freedesktop|deluxe|wikidata|archivematica)$
  http_headers: 
    Access-Control-Allow-Origin: '*'
  static_files: public/latest/\1/\2.sig
  upload: public/latest/(1_10|1_11)/(default|loc|tika|freedesktop|deluxe|wikidata|archivematica).sig$
  secure: always

- url: /(.*\.(html|xml|png|jpg|gif|css|js))$
  static_files: public/\1
  upload: public/.*\.(html|xml|png|jpg|gif|css|js)$
  secure: always

- url: /((about|siegfried|post|categories|tags).*)/$
  static_files: public/\1/index.html
  upload: public/(about|siegfried|post|categories|tags).*/index.html$
  secure: always

- url: /((about|siegfried|post|categories|tags).*)
  static_files: public/\1/index.html
  upload: public/(about|siegfried|post|categories|tags).*/index.html$
  secure: always

- url: /$
  static_files: public/index.html
  upload: public/index.html
  secure: always

- url: /.*
  script: auto
  secure: always