runtime: go
api_version: go1

includes: 
- skiplist.yaml

handlers:
- url: /siegfried/(identify|results|sets|update).*
  script: _go_app
  secure: always

- url: /siegfried/latest
  static_files: public/latest/default.sig
  upload: public/latest/default.sig
  secure: always

- url: /(.*\.(html|xml|png|jpg|gif|css|js))$
  static_files: public/\1
  upload: public/.*\.(html|xml|png|jpg|gif|css|js)$
  secure: always

- url: /((siegfried|posts|categories|tags).*)/$
  static_files: public/\1/index.html
  upload: public/(siegfried|posts|categories|tags).*/index.html
  secure: always

- url: /((siegfried|posts|categories|tags).*)
  static_files: public/\1/index.html
  upload: public/(siegfried|posts|categories|tags).*/index.html
  secure: always

- url: /$
  static_files: public/index.html
  upload: public/index.html
  secure: always

- url: /.*
  script: _go_app
  secure: always







