languageCode = "en-us"
title = "IT for archivists"
baseurl = "https://www.itforarchivists.com"
canonifyURLS = true
theme = "maia"
disableKinds = ["404"]

[taxonomies]
tag = "tags"
category = "categories"

[params]
scheme = "richard"
keywords = "archivists technology"
description = "richard's site"
author = "Richard Lehane"
footer = "© Richard Lehane"
contacts = [
	["twitter", "https://twitter.com/richardlehane", "twitter"],
	["github", "https://github.com/richardlehane", "github"],
	["email", "mailto:richard@itforarchivists.com", "envelope"]
]
pages = [
	["siegfried", "/siegfried", "/img/sf-button.png"]
]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true