languageCode = "en-us"
title = "IT for archivists"
baseurl = "https://www.itforarchivists.com"
canonifyURLS = true
theme = "maia"
disableKinds = ["404"]
googleAnalytics = "UA-15845576-1"

[taxonomies]
tag = "tags"
category = "categories"

[params]
scheme = "richard"
keywords = "archivists technology"
description = "richard's site"
author = "Richard Lehane"
footer = "© Richard Lehane"