package itforarchivists

import (
	"time"

	"github.com/richardlehane/runner"
)

var developJobs = runner.Jobs{
	{
		Detail:   "info - master - Master branch of github.com/richardlehane/siegfried. Corresponds to latest production release.",
		Cmd:      []string{"sf", "-version"},
		RunTwice: false,
		SendOut:  true,
		Base64:   false,
		LogKey:   "setup",
		URL:      "https://www.itforarchivists.com/siegfried/logs/develop",
		Save:     "",
	},
	{
		Detail:   "info - develop - Develop branch of github.com/richardlehane/siegfried. Tip of development and potentially unstable.",
		Cmd:      nil,
		RunTwice: false,
		SendOut:  false,
		Base64:   false,
		LogKey:   "setup",
		URL:      "https://www.itforarchivists.com/siegfried/logs/develop",
		Save:     "",
	},
	{
		Detail:   "corpora dir",
		Cmd:      []string{"mkdir", "/root/corpora"},
		RunTwice: false,
		SendOut:  false,
		Base64:   false,
		LogKey:   "",
		URL:      "https://www.itforarchivists.com/siegfried/logs/develop",
		Save:     "",
	},
	{
		Detail:   "output dir",
		Cmd:      []string{"mkdir", "/root/out"},
		RunTwice: false,
		SendOut:  false,
		Base64:   false,
		LogKey:   "",
		URL:      "https://www.itforarchivists.com/siegfried/logs/develop",
		Save:     "",
	},
	{
		Detail:   "rclone corpora",
		Cmd:      []string{"rclone", "copy", "bb:corpora", "/root/corpora", "--transfers", "32"},
		RunTwice: false,
		SendOut:  false,
		Base64:   false,
		LogKey:   "setup",
		URL:      "https://www.itforarchivists.com/siegfried/logs/develop",
		Save:     "",
	},
	{
		Detail: "save",
		Background: &runner.Background{
			Delay: 30 * time.Second,
			Cmd:   []string{"sfprof", "-multi", "256", "/root/corpora"},
		},
		Cmd:      []string{"curl", "-vs", "-o", "/root/out/sf.prof", "http://localhost:6060/debug/pprof/profile"},
		RunTwice: false,
		SendOut:  false,
		Base64:   false,
		LogKey:   "profile",
		URL:      "https://www.itforarchivists.com/siegfried/logs/develop",
		Save:     "",
	},
	{
		Detail:   "upload",
		Cmd:      []string{"go", "tool", "pprof", "-png", "/root/out/sf.prof"},
		RunTwice: false,
		SendOut:  true,
		Base64:   true,
		LogKey:   "profile",
		URL:      "https://www.itforarchivists.com/siegfried/logs/develop",
		Save:     "",
	},
	{
		Detail:   "master",
		Cmd:      []string{"sf", "-log", "", "-multi", "256", "/root/corpora/ipres-systems-showcase-files"},
		RunTwice: true,
		SendOut:  false,
		Base64:   false,
		LogKey:   "ipres",
		URL:      "https://www.itforarchivists.com/siegfried/logs/develop",
		Save:     "/root/out/sf_ipres.yaml",
	},
	{
		Detail:   "develop",
		Cmd:      []string{"sfdev", "-log", "", "-multi", "256", "/root/corpora/ipres-systems-showcase-files"},
		RunTwice: true,
		SendOut:  false,
		Base64:   false,
		LogKey:   "ipres",
		URL:      "https://www.itforarchivists.com/siegfried/logs/develop",
		Save:     "/root/out/sfdev_ipres.yaml",
	},
	{
		Detail:   "compare - master, develop",
		Cmd:      []string{"roy", "compare", "/root/out/sf_ipres.yaml", "/root/out/sfdev_ipres.yaml"},
		RunTwice: false,
		SendOut:  true,
		Base64:   false,
		LogKey:   "ipres",
		URL:      "https://www.itforarchivists.com/siegfried/logs/develop",
		Save:     "",
	},
	{
		Detail:   "master",
		Cmd:      []string{"sf", "-log", "", "/root/corpora/pronom-files"},
		RunTwice: true,
		SendOut:  false,
		Base64:   false,
		LogKey:   "pronom",
		URL:      "https://www.itforarchivists.com/siegfried/logs/develop",
		Save:     "/root/out/sf_pronom.yaml",
	},
	{
		Detail:   "develop",
		Cmd:      []string{"sfdev", "-log", "", "/root/corpora/pronom-files"},
		RunTwice: true,
		SendOut:  false,
		Base64:   false,
		LogKey:   "pronom",
		URL:      "https://www.itforarchivists.com/siegfried/logs/develop",
		Save:     "/root/out/sfdev_pronom.yaml",
	},
	{
		Detail:   "compare - master, develop",
		Cmd:      []string{"roy", "compare", "/root/out/sf_pronom.yaml", "/root/out/sfdev_pronom.yaml"},
		RunTwice: false,
		SendOut:  true,
		Base64:   false,
		LogKey:   "pronom",
		URL:      "https://www.itforarchivists.com/siegfried/logs/develop",
		Save:     "",
	},
	{
		Detail:   "master",
		Cmd:      []string{"sf", "-log", "", "-multi", "256", "/root/corpora/govdocs-selected"},
		RunTwice: true,
		SendOut:  false,
		Base64:   false,
		LogKey:   "govdocs",
		URL:      "https://www.itforarchivists.com/siegfried/logs/develop",
		Save:     "/root/out/sf_govdocs.yaml",
	},
	{
		Detail:   "develop",
		Cmd:      []string{"sfdev", "-log", "", "-multi", "256", "/root/corpora/govdocs-selected"},
		RunTwice: true,
		SendOut:  false,
		Base64:   false,
		LogKey:   "govdocs",
		URL:      "https://www.itforarchivists.com/siegfried/logs/develop",
		Save:     "/root/out/sfdev_govdocs.yaml",
	},
	{
		Detail:   "compare - master, develop",
		Cmd:      []string{"roy", "compare", "/root/out/sf_govdocs.yaml", "/root/out/sfdev_govdocs.yaml"},
		RunTwice: false,
		SendOut:  true,
		Base64:   false,
		LogKey:   "govdocs",
		URL:      "https://www.itforarchivists.com/siegfried/logs/develop",
		Save:     "",
	},
}

var benchJobs = runner.Jobs{
	{
		Detail:   "info - sf - Siegfried in its default mode (-multi 1).",
		Cmd:      []string{"sf", "-version"},
		RunTwice: false,
		SendOut:  true,
		Base64:   false,
		LogKey:   "setup",
		URL:      "https://www.itforarchivists.com/siegfried/logs/bench",
		Save:     "",
	},
	{
		Detail:   "info - sf multi256 - Siegfried with `sf -multi 256` (sf scans multiple files simultaneously).",
		Cmd:      nil,
		RunTwice: false,
		SendOut:  false,
		Base64:   false,
		LogKey:   "setup",
		URL:      "https://www.itforarchivists.com/siegfried/logs/bench",
		Save:     "",
	},
	{
		Detail:   "info - sf 64k - Siegfried with `sf -multi 256 -sig pronom64.sig` (a buffer of 64k).",
		Cmd:      nil,
		RunTwice: false,
		SendOut:  false,
		Base64:   false,
		LogKey:   "setup",
		URL:      "https://www.itforarchivists.com/siegfried/logs/bench",
		Save:     "",
	},
	{
		Detail:   "info - sf 128k - Siegfried with `sf -multi 256 -sig pronom128.sig` (a buffer of 128k).",
		Cmd:      nil,
		RunTwice: false,
		SendOut:  false,
		Base64:   false,
		LogKey:   "setup",
		URL:      "https://www.itforarchivists.com/siegfried/logs/bench",
		Save:     "",
	},
	{
		Detail:   "info - droid 64k - DROID in its default mode (a buffer of 64K).",
		Cmd:      []string{"droid", "-v"}, // "java", "-jar", "/root/droid/droid-command-line-6.4.jar",
		RunTwice: false,
		SendOut:  true,
		Base64:   false,
		LogKey:   "setup",
		URL:      "https://www.itforarchivists.com/siegfried/logs/bench",
		Save:     "",
	},
	{
		Detail:   "info - droid 128k - DROID with FIDO's default buffer (a buffer of 128K).",
		Cmd:      nil, // "java", "-jar", "/root/droid/droid-command-line-6.4.jar",
		RunTwice: false,
		SendOut:  false,
		Base64:   false,
		LogKey:   "setup",
		URL:      "https://www.itforarchivists.com/siegfried/logs/bench",
		Save:     "",
	},
	{
		Detail:   "info - droid nolimit - DROID without a buffer limit (a buffer of -1).",
		Cmd:      nil, // "java", "-jar", "/root/droid/droid-command-line-6.4.jar",
		RunTwice: false,
		SendOut:  false,
		Base64:   false,
		LogKey:   "setup",
		URL:      "https://www.itforarchivists.com/siegfried/logs/bench",
		Save:     "",
	},
	{
		Detail:   "info - fido 64k - FIDO with DROID's default buffer (a -bufsize of 64K).",
		Cmd:      nil,
		RunTwice: false,
		SendOut:  false,
		Base64:   false,
		LogKey:   "setup",
		URL:      "https://www.itforarchivists.com/siegfried/logs/bench",
		Save:     "",
	},
	{
		Detail:   "info - fido 128k - FIDO in its default mode (a -bufsize of 128K).",
		Cmd:      []string{"fido", "-v"},
		RunTwice: false,
		SendOut:  true,
		Base64:   false,
		LogKey:   "setup",
		URL:      "https://www.itforarchivists.com/siegfried/logs/bench",
		Save:     "",
	},
	{
		Detail:   "info - fido 1mb - FIDO with Archivematica's default buffer (a -bufsize of 1mb).",
		Cmd:      nil,
		RunTwice: false,
		SendOut:  false,
		Base64:   false,
		LogKey:   "setup",
		URL:      "https://www.itforarchivists.com/siegfried/logs/bench",
		Save:     "",
	},
	{
		Detail:   "corpora dir",
		Cmd:      []string{"mkdir", "/root/corpora"},
		RunTwice: false,
		SendOut:  false,
		Base64:   false,
		LogKey:   "",
		URL:      "https://www.itforarchivists.com/siegfried/logs/bench",
		Save:     "",
	},
	{
		Detail:   "output dir",
		Cmd:      []string{"mkdir", "/root/out"},
		RunTwice: false,
		SendOut:  false,
		Base64:   false,
		LogKey:   "",
		URL:      "https://www.itforarchivists.com/siegfried/logs/bench",
		Save:     "",
	},
	{
		Detail:   "rclone corpora",
		Cmd:      []string{"rclone", "copy", "bb:corpora", "/root/corpora", "--transfers", "32"},
		RunTwice: false,
		SendOut:  false,
		Base64:   false,
		LogKey:   "setup",
		URL:      "https://www.itforarchivists.com/siegfried/logs/bench",
		Save:     "",
	},
	{
		Detail:   "droid no archives",
		Cmd:      []string{"sed", "-i", "s/processArchives = true/processArchives = false/", "/root/.droid6/droid.properties"},
		RunTwice: false,
		SendOut:  false,
		Base64:   false,
		LogKey:   "setup",
		URL:      "https://www.itforarchivists.com/siegfried/logs/bench",
		Save:     "",
	},
	{
		Detail:   "roy build 64k",
		Cmd:      []string{"roy", "build", "-name", "64k", "-bof", "65536", "pronom64.sig"},
		RunTwice: false,
		SendOut:  false,
		Base64:   false,
		LogKey:   "setup",
		URL:      "https://www.itforarchivists.com/siegfried/logs/bench",
		Save:     "",
	},
	{
		Detail:   "roy build 128k",
		Cmd:      []string{"roy", "build", "-name", "128k", "-bof", "131072", "pronom128.sig"},
		RunTwice: false,
		SendOut:  false,
		Base64:   false,
		LogKey:   "setup",
		URL:      "https://www.itforarchivists.com/siegfried/logs/bench",
		Save:     "",
	},
	{
		Detail:   "sf",
		Cmd:      []string{"sf", "-log", "", "/root/corpora/ipres-systems-showcase-files"},
		RunTwice: true,
		SendOut:  false,
		Base64:   false,
		LogKey:   "ipres",
		URL:      "https://www.itforarchivists.com/siegfried/logs/bench",
		Save:     "/root/out/sf_ipres.yaml",
	},
	{
		Detail:   "sf multi256",
		Cmd:      []string{"sf", "-log", "", "-multi", "256", "/root/corpora/ipres-systems-showcase-files"},
		RunTwice: true,
		SendOut:  false,
		Base64:   false,
		LogKey:   "ipres",
		URL:      "https://www.itforarchivists.com/siegfried/logs/bench",
		Save:     "/root/out/sfmulti256_ipres.yaml",
	},
	{
		Detail:   "sf 64k",
		Cmd:      []string{"sf", "-log", "", "-multi", "256", "-sig", "pronom64.sig", "/root/corpora/ipres-systems-showcase-files"},
		RunTwice: true,
		SendOut:  false,
		Base64:   false,
		LogKey:   "ipres",
		URL:      "https://www.itforarchivists.com/siegfried/logs/bench",
		Save:     "/root/out/sf64_ipres.yaml",
	},
	{
		Detail:   "sf 128k",
		Cmd:      []string{"sf", "-log", "", "-multi", "256", "-sig", "pronom128.sig", "/root/corpora/ipres-systems-showcase-files"},
		RunTwice: true,
		SendOut:  false,
		Base64:   false,
		LogKey:   "ipres",
		URL:      "https://www.itforarchivists.com/siegfried/logs/bench",
		Save:     "/root/out/sf128_ipres.yaml",
	},
	{
		Detail:   "set droid buffer 64",
		Cmd:      []string{"sed", "-i", "s/maxBytesToScan = -\\?[0-9]*/maxBytesToScan = 65536/", "/root/.droid6/droid.properties"},
		RunTwice: false,
		SendOut:  false,
		Base64:   false,
		LogKey:   "",
		URL:      "https://www.itforarchivists.com/siegfried/logs/bench",
		Save:     "",
	},
	{
		Detail:   "droid 64k",
		Cmd:      []string{"droid", "-a", "/root/corpora/ipres-systems-showcase-files", "-R", "-p", "/root/out/droid64_ipres.droid"},
		RunTwice: true,
		SendOut:  false,
		Base64:   false,
		LogKey:   "ipres",
		URL:      "https://www.itforarchivists.com/siegfried/logs/bench",
		Save:     "",
	},
	{
		Detail:   "convert droid results",
		Cmd:      []string{"droid", "-p", "/root/out/droid64_ipres.droid", "-E", "/root/out/droid64_ipres.csv"},
		RunTwice: false,
		SendOut:  false,
		Base64:   false,
		LogKey:   "",
		URL:      "https://www.itforarchivists.com/siegfried/logs/bench",
		Save:     "",
	},
	{
		Detail:   "set droid buffer 128",
		Cmd:      []string{"sed", "-i", "s/maxBytesToScan = -\\?[0-9]*/maxBytesToScan = 131072/", "/root/.droid6/droid.properties"},
		RunTwice: false,
		SendOut:  false,
		Base64:   false,
		LogKey:   "",
		URL:      "https://www.itforarchivists.com/siegfried/logs/bench",
		Save:     "",
	},
	{
		Detail:   "droid 128k",
		Cmd:      []string{"droid", "-a", "/root/corpora/ipres-systems-showcase-files", "-R", "-p", "/root/out/droid128_ipres.droid"},
		RunTwice: true,
		SendOut:  false,
		Base64:   false,
		LogKey:   "ipres",
		URL:      "https://www.itforarchivists.com/siegfried/logs/bench",
		Save:     "",
	},
	{
		Detail:   "convert droid results",
		Cmd:      []string{"droid", "-p", "/root/out/droid128_ipres.droid", "-E", "/root/out/droid128_ipres.csv"},
		RunTwice: false,
		SendOut:  false,
		Base64:   false,
		LogKey:   "",
		URL:      "https://www.itforarchivists.com/siegfried/logs/bench",
		Save:     "",
	},
	{
		Detail:   "set droid buffer -1",
		Cmd:      []string{"sed", "-i", "s/maxBytesToScan = -\\?[0-9]*/maxBytesToScan = -1/", "/root/.droid6/droid.properties"},
		RunTwice: false,
		SendOut:  false,
		Base64:   false,
		LogKey:   "",
		URL:      "https://www.itforarchivists.com/siegfried/logs/bench",
		Save:     "",
	},
	{
		Detail:   "droid nolimit",
		Cmd:      []string{"droid", "-a", "/root/corpora/ipres-systems-showcase-files", "-R", "-p", "/root/out/droidnl_ipres.droid"},
		RunTwice: true,
		SendOut:  false,
		Base64:   false,
		LogKey:   "ipres",
		URL:      "https://www.itforarchivists.com/siegfried/logs/bench",
		Save:     "",
	},
	{
		Detail:   "convert droid results",
		Cmd:      []string{"droid", "-p", "/root/out/droidnl_ipres.droid", "-E", "/root/out/droidnl_ipres.csv"},
		RunTwice: false,
		SendOut:  false,
		Base64:   false,
		LogKey:   "",
		URL:      "https://www.itforarchivists.com/siegfried/logs/bench",
		Save:     "",
	}, /*
		{
			Detail:   "fido 64k",
			Cmd:      []string{"fido", "-nocontainer", "-recurse", "-bufsize", "65536", "/root/corpora/ipres-systems-showcase-files"},
			Timeout:  time.Minute * 20,
			RunTwice: false,
			SendOut:  false,
			Base64:   false,
			LogKey:   "ipres",
			URL:      "https://www.itforarchivists.com/siegfried/logs/bench",
			Save:     "/root/out/fido64_ipres.csv",
		},
		{
			Detail:   "fido 132k",
			Cmd:      []string{"fido", "-nocontainer", "-recurse", "/root/corpora/ipres-systems-showcase-files"},
			Timeout:  time.Minute * 20,
			RunTwice: false,
			SendOut:  false,
			Base64:   false,
			LogKey:   "ipres",
			URL:      "https://www.itforarchivists.com/siegfried/logs/bench",
			Save:     "/root/out/fido128_ipres.csv",
		},
		{
			Detail:   "fido 1mb",
			Cmd:      []string{"fido", "-nocontainer", "-recurse", "-bufsize", "1048576", "/root/corpora/ipres-systems-showcase-files"},
			Timeout:  time.Minute * 20,
			RunTwice: false,
			SendOut:  false,
			Base64:   false,
			LogKey:   "ipres",
			URL:      "https://www.itforarchivists.com/siegfried/logs/bench",
			Save:     "/root/out/fido1_ipres.csv",
		},*/
	{
		Detail: "compare - sf, sf 64k, sf 128k, droid 64k, droid 128k, droid nolimit",
		Cmd: []string{
			"roy",
			"compare",
			"/root/out/sf_ipres.yaml",
			"/root/out/sf64_ipres.yaml",
			"/root/out/sf128_ipres.yaml",
			"/root/out/droid64_ipres.csv",
			"/root/out/droid128_ipres.csv",
			"/root/out/droidnl_ipres.csv",
		},
		RunTwice: false,
		SendOut:  true,
		Base64:   false,
		LogKey:   "ipres",
		URL:      "https://www.itforarchivists.com/siegfried/logs/bench",
		Save:     "",
	},
	{
		Detail:   "sf",
		Cmd:      []string{"sf", "-log", "", "/root/corpora/pronom-files"},
		RunTwice: true,
		SendOut:  false,
		Base64:   false,
		LogKey:   "pronom",
		URL:      "https://www.itforarchivists.com/siegfried/logs/bench",
		Save:     "/root/out/sf_pronom.yaml",
	},
	{
		Detail:   "sf multi256",
		Cmd:      []string{"sf", "-log", "", "-multi", "256", "/root/corpora/pronom-files"},
		RunTwice: true,
		SendOut:  false,
		Base64:   false,
		LogKey:   "pronom",
		URL:      "https://www.itforarchivists.com/siegfried/logs/bench",
		Save:     "/root/out/sfmulti256_pronom.yaml",
	},
	{
		Detail:   "sf 64k",
		Cmd:      []string{"sf", "-log", "", "-multi", "256", "-sig", "pronom64.sig", "/root/corpora/pronom-files"},
		RunTwice: true,
		SendOut:  false,
		Base64:   false,
		LogKey:   "pronom",
		URL:      "https://www.itforarchivists.com/siegfried/logs/bench",
		Save:     "/root/out/sf64_pronom.yaml",
	},
	{
		Detail:   "sf 128k",
		Cmd:      []string{"sf", "-log", "", "-multi", "256", "-sig", "pronom128.sig", "/root/corpora/pronom-files"},
		RunTwice: true,
		SendOut:  false,
		Base64:   false,
		LogKey:   "pronom",
		URL:      "https://www.itforarchivists.com/siegfried/logs/bench",
		Save:     "/root/out/sf128_pronom.yaml",
	},
	{
		Detail:   "set droid buffer 64",
		Cmd:      []string{"sed", "-i", "s/maxBytesToScan = -\\?[0-9]*/maxBytesToScan = 65536/", "/root/.droid6/droid.properties"},
		RunTwice: false,
		SendOut:  false,
		Base64:   false,
		LogKey:   "",
		URL:      "https://www.itforarchivists.com/siegfried/logs/bench",
		Save:     "",
	},
	{
		Detail:   "droid 64k",
		Cmd:      []string{"droid", "-a", "/root/corpora/pronom-files", "-R", "-p", "/root/out/droid64_pronom.droid"},
		RunTwice: true,
		SendOut:  false,
		Base64:   false,
		LogKey:   "pronom",
		URL:      "https://www.itforarchivists.com/siegfried/logs/bench",
		Save:     "",
	},
	{
		Detail:   "convert droid results",
		Cmd:      []string{"droid", "-p", "/root/out/droid64_pronom.droid", "-E", "/root/out/droid64_pronom.csv"},
		RunTwice: false,
		SendOut:  false,
		Base64:   false,
		LogKey:   "",
		URL:      "https://www.itforarchivists.com/siegfried/logs/bench",
		Save:     "",
	},
	{
		Detail:   "set droid buffer 128",
		Cmd:      []string{"sed", "-i", "s/maxBytesToScan = -\\?[0-9]*/maxBytesToScan = 131072/", "/root/.droid6/droid.properties"},
		RunTwice: false,
		SendOut:  false,
		Base64:   false,
		LogKey:   "",
		URL:      "https://www.itforarchivists.com/siegfried/logs/bench",
		Save:     "",
	},
	{
		Detail:   "droid 128k",
		Cmd:      []string{"droid", "-a", "/root/corpora/pronom-files", "-R", "-p", "/root/out/droid128_pronom.droid"},
		RunTwice: true,
		SendOut:  false,
		Base64:   false,
		LogKey:   "pronom",
		URL:      "https://www.itforarchivists.com/siegfried/logs/bench",
		Save:     "",
	},
	{
		Detail:   "convert droid results",
		Cmd:      []string{"droid", "-p", "/root/out/droid128_pronom.droid", "-E", "/root/out/droid128_pronom.csv"},
		RunTwice: false,
		SendOut:  false,
		Base64:   false,
		LogKey:   "",
		URL:      "https://www.itforarchivists.com/siegfried/logs/bench",
		Save:     "",
	},
	{
		Detail:   "set droid buffer -1",
		Cmd:      []string{"sed", "-i", "s/maxBytesToScan = -\\?[0-9]*/maxBytesToScan = -1/", "/root/.droid6/droid.properties"},
		RunTwice: false,
		SendOut:  false,
		Base64:   false,
		LogKey:   "",
		URL:      "https://www.itforarchivists.com/siegfried/logs/bench",
		Save:     "",
	},
	{
		Detail:   "droid nolimit",
		Cmd:      []string{"droid", "-a", "/root/corpora/pronom-files", "-R", "-p", "/root/out/droidnl_pronom.droid"},
		RunTwice: true,
		SendOut:  false,
		Base64:   false,
		LogKey:   "pronom",
		URL:      "https://www.itforarchivists.com/siegfried/logs/bench",
		Save:     "",
	},
	{
		Detail:   "convert droid results",
		Cmd:      []string{"droid", "-p", "/root/out/droidnl_pronom.droid", "-E", "/root/out/droidnl_pronom.csv"},
		RunTwice: false,
		SendOut:  false,
		Base64:   false,
		LogKey:   "",
		URL:      "https://www.itforarchivists.com/siegfried/logs/bench",
		Save:     "",
	}, /*
		{
			Detail:   "fido 64k",
			Cmd:      []string{"fido", "-nocontainer", "-recurse", "-bufsize", "65536", "/root/corpora/pronom-files"},
			Timeout:  time.Minute * 20,
			RunTwice: true,
			SendOut:  false,
			Base64:   false,
			LogKey:   "pronom",
			URL:      "https://www.itforarchivists.com/siegfried/logs/bench",
			Save:     "/root/out/fido64_pronom.csv",
		},
		{
			Detail:   "fido 132k",
			Cmd:      []string{"fido", "-nocontainer", "-recurse", "/root/corpora/pronom-files"},
			Timeout:  time.Minute * 20,
			RunTwice: true,
			SendOut:  false,
			Base64:   false,
			LogKey:   "pronom",
			URL:      "https://www.itforarchivists.com/siegfried/logs/bench",
			Save:     "/root/out/fido128_pronom.csv",
		},
		{
			Detail:   "fido 1mb",
			Cmd:      []string{"fido", "-nocontainer", "-recurse", "-bufsize", "1048576", "/root/corpora/pronom-files"},
			Timeout:  time.Minute * 20,
			RunTwice: true,
			SendOut:  false,
			Base64:   false,
			LogKey:   "pronom",
			URL:      "https://www.itforarchivists.com/siegfried/logs/bench",
			Save:     "/root/out/fido1_pronom.csv",
		},*/
	{
		Detail: "compare - sf, sf 64k, sf 128k, droid 64k, droid 128k, droid nolimit",
		Cmd: []string{
			"roy",
			"compare",
			"/root/out/sf_pronom.yaml",
			"/root/out/sf64_pronom.yaml",
			"/root/out/sf128_pronom.yaml",
			"/root/out/droid64_pronom.csv",
			"/root/out/droid128_pronom.csv",
			"/root/out/droidnl_pronom.csv",
		},
		RunTwice: false,
		SendOut:  true,
		Base64:   false,
		LogKey:   "pronom",
		URL:      "https://www.itforarchivists.com/siegfried/logs/bench",
		Save:     "",
	},
	{
		Detail:   "sf",
		Cmd:      []string{"sf", "-log", "", "/root/corpora/govdocs-selected"},
		RunTwice: true,
		SendOut:  false,
		Base64:   false,
		LogKey:   "govdocs",
		URL:      "https://www.itforarchivists.com/siegfried/logs/bench",
		Save:     "/root/out/sf_govdocs.yaml",
	},
	{
		Detail:   "sf multi256",
		Cmd:      []string{"sf", "-log", "", "-multi", "256", "/root/corpora/govdocs-selected"},
		RunTwice: true,
		SendOut:  false,
		Base64:   false,
		LogKey:   "govdocs",
		URL:      "https://www.itforarchivists.com/siegfried/logs/bench",
		Save:     "/root/out/sfmulti256_govdocs.yaml",
	},
	{
		Detail:   "sf 64k",
		Cmd:      []string{"sf", "-log", "", "-multi", "256", "-sig", "pronom64.sig", "/root/corpora/govdocs-selected"},
		RunTwice: true,
		SendOut:  false,
		Base64:   false,
		LogKey:   "govdocs",
		URL:      "https://www.itforarchivists.com/siegfried/logs/bench",
		Save:     "/root/out/sf64_govdocs.yaml",
	},
	{
		Detail:   "sf 128k",
		Cmd:      []string{"sf", "-log", "", "-multi", "256", "-sig", "pronom128.sig", "/root/corpora/govdocs-selected"},
		RunTwice: true,
		SendOut:  false,
		Base64:   false,
		LogKey:   "govdocs",
		URL:      "https://www.itforarchivists.com/siegfried/logs/bench",
		Save:     "/root/out/sf128_govdocs.yaml",
	},
	{
		Detail:   "set droid buffer 64",
		Cmd:      []string{"sed", "-i", "s/maxBytesToScan = -\\?[0-9]*/maxBytesToScan = 65536/", "/root/.droid6/droid.properties"},
		RunTwice: false,
		SendOut:  false,
		Base64:   false,
		LogKey:   "",
		URL:      "https://www.itforarchivists.com/siegfried/logs/bench",
		Save:     "",
	},
	{
		Detail:   "droid 64k",
		Cmd:      []string{"droid", "-a", "/root/corpora/govdocs-selected", "-R", "-p", "/root/out/droid64_govdocs.droid"},
		RunTwice: true,
		SendOut:  false,
		Base64:   false,
		LogKey:   "govdocs",
		URL:      "https://www.itforarchivists.com/siegfried/logs/bench",
		Save:     "",
	},
	{
		Detail:   "convert droid results",
		Cmd:      []string{"droid", "-p", "/root/out/droid64_govdocs.droid", "-E", "/root/out/droid64_govdocs.csv"},
		RunTwice: false,
		SendOut:  false,
		Base64:   false,
		LogKey:   "",
		URL:      "https://www.itforarchivists.com/siegfried/logs/bench",
		Save:     "",
	},
	{
		Detail:   "set droid buffer 128",
		Cmd:      []string{"sed", "-i", "s/maxBytesToScan = -\\?[0-9]*/maxBytesToScan = 131072/", "/root/.droid6/droid.properties"},
		RunTwice: false,
		SendOut:  false,
		Base64:   false,
		LogKey:   "",
		URL:      "https://www.itforarchivists.com/siegfried/logs/bench",
		Save:     "",
	},
	{
		Detail:   "droid 128k",
		Cmd:      []string{"droid", "-a", "/root/corpora/govdocs-selected", "-R", "-p", "/root/out/droid128_govdocs.droid"},
		RunTwice: true,
		SendOut:  false,
		Base64:   false,
		LogKey:   "govdocs",
		URL:      "https://www.itforarchivists.com/siegfried/logs/bench",
		Save:     "",
	},
	{
		Detail:   "convert droid results",
		Cmd:      []string{"droid", "-p", "/root/out/droid128_govdocs.droid", "-E", "/root/out/droid128_govdocs.csv"},
		RunTwice: false,
		SendOut:  false,
		Base64:   false,
		LogKey:   "",
		URL:      "https://www.itforarchivists.com/siegfried/logs/bench",
		Save:     "",
	},
	{
		Detail:   "set droid buffer -1",
		Cmd:      []string{"sed", "-i", "s/maxBytesToScan = -\\?[0-9]*/maxBytesToScan = -1/", "/root/.droid6/droid.properties"},
		RunTwice: false,
		SendOut:  false,
		Base64:   false,
		LogKey:   "",
		URL:      "https://www.itforarchivists.com/siegfried/logs/bench",
		Save:     "",
	},
	{
		Detail:   "droid nolimit",
		Cmd:      []string{"droid", "-a", "/root/corpora/govdocs-selected", "-R", "-p", "/root/out/droidnl_govdocs.droid"},
		RunTwice: true,
		SendOut:  false,
		Base64:   false,
		LogKey:   "govdocs",
		URL:      "https://www.itforarchivists.com/siegfried/logs/bench",
		Save:     "",
	},
	{
		Detail:   "convert droid results",
		Cmd:      []string{"droid", "-p", "/root/out/droidnl_govdocs.droid", "-E", "/root/out/droidnl_govdocs.csv"},
		RunTwice: false,
		SendOut:  false,
		Base64:   false,
		LogKey:   "",
		URL:      "https://www.itforarchivists.com/siegfried/logs/bench",
		Save:     "",
	}, /*
		{
			Detail:   "fido 64k",
			Cmd:      []string{"fido", "-recurse", "-bufsize", "65536", "/root/corpora/govdocs-selected"},
			Timeout:  time.Minute * 30,
			RunTwice: false,
			SendOut:  false,
			Base64:   false,
			LogKey:   "govdocs",
			URL:      "https://www.itforarchivists.com/siegfried/logs/bench",
			Save:     "/root/out/fido64_govdocs.csv",
		},
		{
			Detail:   "fido 128k",
			Cmd:      []string{"fido", "-recurse", "/root/corpora/govdocs-selected"},
			Timeout:  time.Minute * 30,
			RunTwice: false,
			SendOut:  false,
			Base64:   false,
			LogKey:   "govdocs",
			URL:      "https://www.itforarchivists.com/siegfried/logs/bench",
			Save:     "/root/out/fido128_govdocs.csv",
		},
		{
			Detail:   "fido 1mb",
			Cmd:      []string{"fido", "-recurse", "-bufsize", "1048576", "/root/corpora/govdocs-selected"},
			Timeout:  time.Minute * 30,
			RunTwice: false,
			SendOut:  false,
			Base64:   false,
			LogKey:   "govdocs",
			URL:      "https://www.itforarchivists.com/siegfried/logs/bench",
			Save:     "/root/out/fido1_govdocs.csv",
		},*/
	{
		Detail: "compare - sf, sf 64k, sf 128k, droid 64k, droid 128k, droid nolimit",
		Cmd: []string{
			"roy",
			"compare",
			"/root/out/sf_govdocs.yaml",
			"/root/out/sf64_govdocs.yaml",
			"/root/out/sf128_govdocs.yaml",
			"/root/out/droid64_govdocs.csv",
			"/root/out/droid128_govdocs.csv",
			"/root/out/droidnl_govdocs.csv",
		},
		RunTwice: false,
		SendOut:  true,
		Base64:   false,
		LogKey:   "govdocs",
		URL:      "https://www.itforarchivists.com/siegfried/logs/bench",
		Save:     "",
	},
}
