# This workflow tests the debian repository for siegfried.
#
# Trigger it by a push.
name: ReplaceAptKey
on:
  push:
jobs:
  bench:
    runs-on: ubuntu-latest
    steps:
      - name: Test debian repository with a new key method
        run: |
          sudo gpg --no-default-keyring --keyring /usr/share/keyrings/siegfried-archive-keyring.gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 20F802FE798E6857
          echo "deb [signed-by=/usr/share/keyrings/siegfried-archive-keyring.gpg] https://www.itforarchivists.com/ buster main" | sudo tee -a /etc/apt/sources.list.d/siegfried.list
          sudo apt-get update && sudo apt-get install siegfried
          sf -v